"""
╔══════════════════════════════════════════════════════════════════╗
║               📚  S E N S E I  —  AI Study Companion            ║
║          Inspired by Tradition. Powered by Intelligence.         ║
╚══════════════════════════════════════════════════════════════════╝

File            : sensei_fs_v9.0.py
Author          : Yousuf S. R. Sakkaf
Status          : Completed (Phase 1)
Release Date    : 17/05/2026
Version         : 9.0

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 OVERVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Sensei is an AI-powered educational assistant that transforms static
study materials — PDFs, Jupyter Notebooks, and PowerPoint slides —
into a fully interactive, conversational learning experience.

Powered by Google Gemini, Sensei acts as a virtual tutor. When a
student asks a question, it searches their own uploaded documents for
relevant content, then constructs a clear, structured explanation
grounded entirely in that material. No hallucinations. No generic
answers. Everything is traceable back to the source.

The response architecture is intentionally two-layered:
  1. A concise, tutor-style Main Explanation generated by Gemini.
  2. The exact raw source excerpts displayed in collapsible expanders,
     so the student can verify every claim against their own notes.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 CORE CAPABILITIES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ▸ Multi-Format Ingestion
      Natively parses PDF (.pdf), Jupyter Notebook (.ipynb), and
      PowerPoint (.pptx) without any external conversion tools.

  ▸ Keyword-Based Retrieval Engine
      Each document is chunked and scored against the user's question
      keywords. The top-3 most relevant chunks per source are passed
      to Gemini as grounded context. Fully explainable — no black box.

  ▸ Slide-Aware PPTX Parsing
      Each slide is extracted as a self-contained atomic chunk labeled
      [Slide N]. Slides never bleed into each other during retrieval.

  ▸ Notebook Code Rendering
      Code cells are wrapped in fenced Python blocks for
      syntax-highlighted display. Markdown cells render as-is.

  ▸ Source Transparency
      Retrieved excerpts are always shown in dedicated expanders
      alongside the AI answer, colour-coded by source type.

  ▸ Per-Session Isolation
      Every user gets a UUID-namespaced session. Chat history and
      document state are stored in sessions/ and never shared across
      users. Age-based cleanup removes abandoned sessions after 2h.

  ▸ Dojo Mode Interface
      A premium neo-traditional dark theme with teal and gold accents,
      animated gradient strip, glowing borders, and a deep forest
      background — visually distinct from the default theme.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ARCHITECTURAL PHILOSOPHY  (Phase 1 — Keyword Retrieval)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This build intentionally bypasses Vector Databases (Chroma, Pinecone)
and Embedding Pipelines in favour of a lightweight, JSON-serialised
keyword retrieval system. This design choice ensures:

  • Zero infrastructure overhead — no external services required.
  • Maximum explainability — every retrieved chunk is directly
    readable and traceable to the source file.
  • Ease of maintenance — the retrieval logic is plain Python that
    any developer can read, modify, and extend.
  • Educational clarity — the codebase itself teaches RAG fundamentals
    without hiding complexity behind heavy frameworks.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 CHANGELOG
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
v9.0 — 17/05/2026
  • Version milestone bump to 9.0 marking Phase 1 public release.
  • Renamed file to sensei_fs_v9_0.py.

v8.7 — 17/05/2026
  • Rewrote module docstring with full structure, filename field,
    and detailed section headers for professional readability.
  • Added annotated import block — every import now has an inline
    comment explaining its role.
  • Added comprehensive inline comments throughout the entire
    codebase: file readers, retrieval engine, normaliser, session
    init, UI sections, and chat pipeline — readable by both
    beginners and experienced developers.

v8.6 — 16/05/2026
  • Moved all JSON session files into a dedicated sessions/ subfolder
    (auto-created on startup). Root directory stays clean.
  • Replaced blanket-delete cleanup (v8.5) with age-based cleanup:
    only session files older than 2 hours are removed — safe for
    concurrent multi-user deployments.
  • One-time migration: legacy root-level chat.json / documents.json
    deleted on first v8.6 startup.
  • All imports (glob, time, uuid) consolidated at top of file.
  • 10MB document size guard added before writing DOCS_FILE.
  • Rolling 50-turn chat limit prevents unbounded CHAT_FILE growth.

v8.5 — 16/05/2026
  • Age-based stale file cleanup on session startup.

v8.4 — 16/05/2026
  • PPTX multi-slide bleed fixed: context window disabled for slides.
  • Dojo Mode rebalanced to equal teal + gold visual presence.

v8.3 — 16/05/2026
  • PPTX retrieval pollution fixed: slide labels embedded inline
    as [Slide N] instead of standalone ### headings.
  • Chunk splitter updated to handle --- slide separators.
  • Dojo Mode CSS overhauled for strong visual distinction.

v8.2 — 16/05/2026
  • Dead code removed. normalize_markdown and render_notebook_content
    cleaned. read_pptx made slide-aware with ### Slide N headings.

v8.1 — 15/05/2026
  • read_ipynb upgraded: code cells wrapped in fenced Python blocks.
  • Keyword extraction switched to regex word boundaries.
  • Cross-platform path handling via os.path.join.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 FUTURE ROADMAP
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  → Migration to modern google-genai SDK.
  → Vector database integration (Phase 2) for semantic search.
  → Excel (.xlsx) and Word (.docx) document parsing.
  → Multi-language support.
  → Quiz generation from uploaded material.
"""

# -------------------------------
# 📦 IMPORTS
# -------------------------------
import streamlit as st                        # Core web app framework — handles UI, state, and layout
import google.generativeai as genai           # Google Gemini API — the AI model that generates answers
from PyPDF2 import PdfReader                  # Extracts raw text from PDF files page by page
from pptx import Presentation                 # Reads PowerPoint files and extracts text from each slide shape
import json                                   # Serialises/deserialises Python dicts to/from .json files on disk
import os                                     # File system operations: paths, file existence checks, deletion
import re                                     # Regular expressions — used for text cleaning and keyword extraction
import base64                                 # Decodes base64-encoded images embedded inside Jupyter notebooks
import glob                                   # Pattern-based file searching (e.g. finding all chat_*.json files)
import time                                   # Used to get current timestamp for age-based session file cleanup
import uuid                                   # Generates unique session IDs so each user's files don't collide
from io import BytesIO                        # Wraps raw bytes as a file-like object (used for image handling)
from PIL import Image                         # Opens and displays image files — used to load the Sensei logo

# -------------------------------
# 🔑 CONFIG
# -------------------------------
# Build the logo path using os.path.join so it works on both
# Windows (backslash) and Mac/Linux (forward slash) automatically.
image_path = os.path.join("Assets", "Sensei_v1.png")
logo = Image.open(image_path)

# -------------------------------
# 🔐 API KEY SYSTEM
# -------------------------------
# Streamlit reruns the entire script on every user interaction.
# st.session_state persists values across reruns within the same session.
# We initialise these flags once so they don't reset on every rerun.

if "api_configured" not in st.session_state:
    st.session_state.api_configured = False   # Tracks whether a valid API key has been connected

if "api_status" not in st.session_state:
    st.session_state.api_status = None        # Holds the status message shown below the Connect button

if "model" not in st.session_state:
    st.session_state.model = None             # Holds the live Gemini model object after successful connection


# -------------------------------
# 🧠 SESSION INIT
# -------------------------------

# Sessions directory — all JSON files live here, never in the root
SESSIONS_DIR = "sessions"
os.makedirs(SESSIONS_DIR, exist_ok=True)

if "initialized" not in st.session_state:
    st.session_state.initialized = True

    # One-time migration: delete legacy root-level chat.json / documents.json
    # left over from versions prior to UUID namespacing
    for legacy in ["chat.json", "documents.json"]:
        try:
            os.remove(legacy)
        except OSError:
            pass

    # Age-based cleanup: delete session files abandoned for more than 2 hours.
    # Safe for multi-user — only touches files that are definitely inactive.
    cutoff = time.time() - (2 * 60 * 60)
    for stale in glob.glob(os.path.join(SESSIONS_DIR, "chat_*.json")) + \
                 glob.glob(os.path.join(SESSIONS_DIR, "documents_*.json")):
        try:
            if os.path.getmtime(stale) < cutoff:
                os.remove(stale)
        except OSError:
            pass  # Already removed by another process — safe to ignore

    # Generate a unique session ID to namespace files for this session
    st.session_state.session_id = uuid.uuid4().hex

# Derive per-session file paths inside the sessions folder
_sid = st.session_state.session_id
CHAT_FILE = os.path.join(SESSIONS_DIR, f"chat_{_sid}.json")
DOCS_FILE = os.path.join(SESSIONS_DIR, f"documents_{_sid}.json")

# -------------------------------
# 📄 FILE READERS
# -------------------------------

def sanitize_text(text):
    """Removes illegal surrogate characters that crash Streamlit rendering."""
    # This regex strips out the corrupted unicode ranges (U+D800 to U+DFFF)
    return re.sub(r'[\ud800-\udfff]', '', text)

# Each reader receives a Streamlit UploadedFile object and returns
# a single plain-text string representing the document's content.
# That string is stored in the documents dict and later chunked
# by the retrieval engine.

def read_pdf(file):
    # PdfReader opens the PDF and gives access to each page.
    # extract_text() can return None on image-only pages, so
    # we use `or ""` to safely fall back to an empty string.
    reader = PdfReader(file)
    # Changed "" to "\n\n" to ensure pages are split into separate chunks!
    full_text = "\n\n".join([p.extract_text() or "" for p in reader.pages])
    return sanitize_text(full_text)


def read_ipynb(file):
    # Jupyter notebooks are JSON files containing a list of cells.
    # Each cell has a type ("code" or "markdown") and a source list
    # of strings which we join into one string per cell.
    data = json.load(file)
    formatted_content = []

    for cell in data["cells"]:
        cell_type = cell.get("cell_type", "")
        source = "".join(cell.get("source", ""))

        if cell_type == "code":
            # Wrap code cells in fenced Python blocks so Streamlit
            # renders them with syntax highlighting in the expander.
            formatted_content.append(f"```python\n{source}\n```")
        else:
            # Markdown cells (explanations, headings, notes) are kept
            # as-is since st.markdown() will render them correctly.
            formatted_content.append(source)

    # Separate each cell with a blank line so the chunker
    # can split on \n\n later during retrieval.
    full_text = "\n\n".join(formatted_content)
    return sanitize_text(full_text)


def read_pptx(file):
    # python-pptx gives access to each slide and its shapes.
    # A "shape" can be a text box, title, or content placeholder.
    # We extract text from every shape that has non-empty text.
    prs = Presentation(file)
    slides_text = []

    for i, slide in enumerate(prs.slides):
        slide_content = []
        for shape in slide.shapes:
            if hasattr(shape, "text") and shape.text.strip():
                slide_content.append(shape.text.strip())

        if slide_content:
            # The slide label [Slide N] is embedded as the FIRST LINE
            # of the chunk body — not as a separate paragraph.
            # This is critical: a standalone heading paragraph would
            # become its own scoreable chunk in the retrieval engine,
            # causing the wrong slide's content to be returned.
            body = "\n\n".join(slide_content)
            slides_text.append(f"[Slide {i+1}]\n{body}")

    # Slides are separated by a distinctive --- marker.
    # The retrieval engine splits on this marker first, so each slide
    # becomes one atomic chunk that is never split mid-slide.
    full_text = "\n\n---\n\n".join(slides_text)
    return sanitize_text(full_text)


# -------------------------------
# 🧹 MARKDOWN NORMALIZER
# -------------------------------
def normalize_markdown(text):
    """
    Cleans raw extracted text before displaying it in the UI.
    Handles common issues from PDF extraction: broken line endings,
    excessive blank lines, and malformed heading syntax.
    """
    # Standardise Windows-style line endings (\r\n) to Unix (\n)
    text = text.replace("\r\n", "\n")

    # PDFs often wrap long sentences mid-word at page column boundaries,
    # inserting a single \n that isn't a real paragraph break. This regex
    # removes those soft line breaks while preserving intentional paragraph
    # separations (which use double \n\n).
    text = re.sub(r'(?<!\n)\n(?!\n)', ' ', text)

    # Collapse 3 or more consecutive blank lines down to 2.
    # Keeps visual spacing clean without excessive gaps.
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Ensure markdown headings always have a space after the # symbol.
    # Without this, "#Heading" won't render as a heading — it stays as raw text.
    text = re.sub(r'(?m)^#([^\s])', r'# \1', text)

    return text.strip()


# -------------------------------
# 🧹 CHUNK FORMATTER FOR EXPANDERS
# -------------------------------
def format_chunks_for_display(raw_text, source_type):
    """
    Prepares retrieved source text for display inside the expander UI.
    Deduplicates, splits into readable paragraphs, and filters out noise.

    Args:
        raw_text    : The combined retrieved chunk string from the engine.
        source_type : "pdf", "notebook", or "slides" — reserved for future
                      source-specific formatting rules.
    Returns:
        List of clean paragraph strings, each rendered as a separate block.
    """
    # Remove duplicate lines (common in PDFs with repeated headers/footers)
    cleaned = clean_retrieved_content(raw_text)

    # Split the cleaned text into paragraph-level blocks using double newlines
    chunks = [c.strip() for c in cleaned.split("\n\n") if c.strip()]

    # Filter out noise: very short fragments (< 30 chars) that aren't headings.
    # These are usually stray punctuation, page numbers, or extraction artefacts.
    chunks = [
        c for c in chunks
        if len(c) >= 30 or c.startswith("#")
    ]

    return chunks


# -------------------------------
# 🖼️ RENDER NOTEBOOK MARKDOWN
# -------------------------------
def render_notebook_content(content):
    """
    Renders a notebook's extracted text in the Streamlit UI.
    Handles the special case of inline base64 images that PyPDF2/nbformat
    may embed directly in the source — these are stripped from the text
    and rendered separately as st.image() calls below the text.
    """
    # Regex pattern to detect embedded base64 images in markdown image syntax:
    # ![alt text](data:image/png;base64,<very long string>)
    pattern = r'!\[.*?\]\((data:image\/.*?;base64,.*?)\)'

    # Capture all embedded image data URIs before removing them from text
    matches = re.findall(pattern, content)

    # Replace inline base64 blobs with a human-readable placeholder.
    # Leaving them in would make the markdown output unreadable.
    cleaned_text = re.sub(pattern, '*[Image omitted from text]*', content)

    # Collapse any excessive blank lines introduced by the substitution
    cleaned_text = re.sub(r'\n{3,}', '\n\n', cleaned_text)

    # Render the cleaned markdown text (includes fenced code blocks)
    st.markdown(cleaned_text)

    # Render any extracted images below the text as actual image widgets
    for image_data in matches:
        try:
            header, encoded = image_data.split(",", 1)
            image_bytes = base64.b64decode(encoded)
            st.image(image_bytes)
        except:
            # If decoding fails for any reason, silently skip — don't crash
            pass


# -------------------------------
# 🧼 RETRIEVED CONTENT CLEANER
# -------------------------------
def clean_retrieved_content(text):
    """
    Removes duplicate lines from retrieved text.
    PDFs often repeat headers, footers, and slide titles across pages.
    This function keeps the first occurrence of any line and drops repeats.
    Blank lines are always preserved to maintain paragraph structure.
    """
    lines = text.splitlines()
    seen = set()   # Tracks normalised (lowercased, stripped) lines we've already kept
    cleaned = []

    for line in lines:
        # Normalise for comparison: strip whitespace and lowercase.
        # We compare normalised but append the original to preserve formatting.
        normalized = line.strip().lower()

        if normalized == "":
            # Always keep blank lines — they define paragraph boundaries
            cleaned.append(line)
            continue

        if normalized not in seen:
            seen.add(normalized)
            cleaned.append(line)
        # If already seen, silently skip — duplicate line dropped

    return "\n".join(cleaned)

# -------------------------------
# 🔍 RETRIEVAL ENGINE
# -------------------------------
def find_relevant_sources(question, documents):
    """
    Searches all uploaded documents for chunks most relevant to the question.

    Algorithm:
      1. Extract meaningful keywords from the question (stop words removed).
      2. For each document source, split text into chunks.
      3. Score each chunk by counting how many keywords it contains.
      4. Expand top chunks with neighbouring context (PDF/notebook only).
      5. Return top-3 chunks per source, deduplicated.

    Args:
        question  : The user's raw question string.
        documents : Dict mapping source type ("pdf", "notebook", "slides")
                    to the full extracted text string.
    Returns:
        List of (source, combined_text) tuples for the most relevant excerpts.
    """
    results = []

    # Common English words that carry no topical meaning.
    # Removing these ensures only meaningful content words are matched.
    stop_words = {
        "what", "is", "are", "the", "how", "and",
        "of", "to", "in", "for", "a", "an",
        "can", "you", "explain", "with", "which", "tell",
        "me", "summarise", "write", "about", "from",
        "list", "give", "define", "does"
    }

    # \b\w+\b extracts whole words only, ignoring surrounding punctuation.
    # e.g. "what's" → ["what", "s"], "AI-powered" → ["AI", "powered"]
    raw_words = re.findall(r'\b\w+\b', question.lower())
    keywords = [word for word in raw_words if word not in stop_words]

    for source, text in documents.items():

        # Split on the --- slide separator first (PPTX), then on double
        # newlines (PDF/notebook). This ensures each slide stays as one
        # atomic unit and never gets split mid-content.
        raw_chunks = re.split(r'\n\n---\n\n|\n\n', text)
        chunks = [c.strip() for c in raw_chunks if c.strip()]

        scored_chunks = []

        for chunk_index, chunk in enumerate(chunks):

            chunk_lower = chunk.lower()

            # Very long chunks (> 1500 chars) are truncated rather than skipped.
            # Skipping would silently drop relevant content from large PDF pages.
            if len(chunk) > 1500:
                chunk = chunk[:1500]
                chunk_lower = chunk.lower()

            # Count how many question keywords appear in this chunk.
            # Higher score = more topically relevant to the question.
            score = sum(1 for keyword in keywords if keyword in chunk_lower)

            if score >= 1:  # At least one keyword must match to be considered

                if source == "slides":
                    # Slides are self-contained units. Expanding into neighbouring
                    # slides would pull in completely unrelated topics, so we
                    # return the matched slide chunk exactly as-is.
                    expanded_chunk = chunk
                else:
                    # For PDF and notebook, surrounding paragraphs often provide
                    # helpful context (e.g. a definition followed by an example).
                    # We grab the chunk plus one paragraph before and after it.
                    context_window = chunks[
                        max(0, chunk_index - 1):
                        min(len(chunks), chunk_index + 2)
                    ]
                    expanded_chunk = "\n\n".join(context_window)

                scored_chunks.append((score, expanded_chunk.strip()))

        # Sort chunks by relevance score descending — highest match first
        scored_chunks.sort(key=lambda x: x[0], reverse=True)

        # Take the top 3 most relevant chunks for this source
        top_chunks = [chunk for score, chunk in scored_chunks[:3]]

        # dict.fromkeys preserves insertion order while removing exact duplicates.
        # This handles the case where context window expansion causes two adjacent
        # chunks to produce identical expanded strings.
        top_chunks = list(dict.fromkeys(top_chunks))

        if top_chunks:
            # Combine the top chunks into one string for this source,
            # separated by blank lines to preserve readability.
            combined = "\n\n".join(top_chunks)
            results.append((source, combined))

    return results


# -------------------------------
# 🤖 GEMINI RESPONSE GENERATOR
# -------------------------------
def generate_summary(question, relevant_sources):
    """
    Sends the retrieved context and user question to Google Gemini
    and returns a structured tutor-style explanation.

    The context is capped at 1000 characters per source to stay within
    safe token limits and keep the prompt focused.
    """
    # Build the context block from all retrieved source chunks
    context = ""
    for _, text in relevant_sources:
        context += text[:1000] + "\n\n"   # Cap per-source context to 1000 chars

    # The prompt instructs Gemini to stay grounded in the provided context
    # and respond as a tutor — clear language, examples, structured output.
    prompt = f"""
    You are Sensei, an expert tutor.

    Provide a clear, concise explanation.
    Use simple language and examples.

    Context:
    {context}

    Question:
    {question}
    """

    # generate_content() sends the prompt to the Gemini model and returns
    # a response object. .text extracts the plain string from it.
    return st.session_state.model.generate_content(prompt).text



# -------------------------------
# 🎨 UI
# -------------------------------

st.set_page_config(
    page_title="Sensei AI",
    page_icon=logo,
    layout="wide"
)

st.markdown("""
<style>

/* -------------------------------
   GLOBAL
--------------------------------*/

html, body, [class*="css"] {
    font-family: 'Segoe UI', sans-serif;
}

/* -------------------------------
   MAIN CONTAINER
--------------------------------*/

.block-container {
    padding-top: 2rem;
    padding-bottom: 2rem;
}

/* -------------------------------
   HEADER
--------------------------------*/

.main-header {
    padding: 1.5rem;
    border-radius: 20px;
    background: linear-gradient(
        135deg,
        rgba(40,40,60,0.95),
        rgba(25,25,35,0.95)
    );
    margin-bottom: 2rem;
    border: 1px solid rgba(255,255,255,0.08);
}

.logo-section {
    display: flex;
    align-items: center;
    gap: 20px;
}

.logo-circle {
    width: 70px;
    height: 70px;
    border-radius: 50%;
    background: linear-gradient(135deg, #4F46E5, #06B6D4);
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 32px;
    box-shadow: 0 0 20px rgba(79,70,229,0.4);
}

.main-header h1 {
    margin: 0;
    font-size: 2.8rem;
    color: white;
}

.main-header p {
    margin-top: 5px;
    color: #b0b0b0;
    font-size: 1rem;
}

/* -------------------------------
   CHAT INPUT
--------------------------------*/

.stChatInputContainer {
    border-radius: 20px;
}

/* -------------------------------
   EXPANDERS
--------------------------------*/

.streamlit-expanderHeader {
    font-size: 1rem;
    font-weight: 600;
}

/* -------------------------------
   SIDEBAR
--------------------------------*/

section[data-testid="stSidebar"] {
    background-color: #161A22;
    border-right: 1px solid rgba(255,255,255,0.08);
}

/* -------------------------------
   FOOTER
--------------------------------*/

.footer {
    margin-top: 4rem;
    text-align: center;
    color: #888;
    font-size: 0.9rem;
    padding: 1rem;
}

</style>
""", unsafe_allow_html=True)

# -------------------------------
# 📂 SIDEBAR
# -------------------------------
with st.sidebar:
    st.image(logo, width=80)
    st.markdown("## Sensei")
    st.caption("Inspired by Tradition. Powered by Intelligence.")
    st.markdown("""
    <div class="upload-tip" style="color: #D1D5DB !important;">
    A next-generation AI learning companion designed
    to combine traditional mentorship principles with
    modern contextual intelligence.
    </div>
    """, unsafe_allow_html=True)

    dojo_mode = st.toggle("🥷 Enable Dojo Mode")
    st.markdown("---")
    
    # -------------------------------
    # 🔑 GEMINI API
    # -------------------------------

    st.markdown("### 🔑 Gemini API")

    user_api_key = st.text_input(
        "Enter Gemini API Key",
        type="password",
        placeholder="Paste your API key here..."
    )

    if st.button("✅ Connect API"):

        if user_api_key.strip() == "":
            st.session_state.api_status = "empty"

        else:
            try:
                genai.configure(api_key=user_api_key)
                test_model = genai.GenerativeModel("gemini-3-flash-preview")
                test_model.generate_content("Hello") # Real validation

                st.session_state.model = test_model
                st.session_state.api_configured = True
                st.session_state.api_status = "success"

            except Exception as e:
                st.session_state.api_configured = False
                st.session_state.model = None
                
                print(f"🚨 GEMINI CONNECTION FAILED: {e}") 
                
                # Assign a specific status instead of drawing the error here
                if "429" in str(e):
                    st.session_state.api_status = "quota"
                elif "500" in str(e):
                    st.session_state.api_status = "server"
                elif "400" in str(e):
                    st.session_state.api_status = "model"
                else:
                    st.session_state.api_status = "error"

    # Draw ONE clean message based on the exact status
    if st.session_state.api_status == "success":
        st.success("Gemini API connected successfully.")
    elif st.session_state.api_status == "quota":
        st.error("⚠️ Quota Exceeded: You have hit the Gemini API rate limit. Please wait a few minutes.")
    elif st.session_state.api_status == "server":
        st.error("⚠️ Internal Error: The Gemini service is currently unavailable.")
    elif st.session_state.api_status == "model":
        st.error("⚠️ Invalid Model: 'gemini-3-flash-preview' may be deprecated.")
    elif st.session_state.api_status == "error":
        st.error("⚠️ Connection Failed: Invalid API key or network error.")
    elif st.session_state.api_status == "empty":
        st.warning("Please enter a valid API key.")

    uploaded_files = st.file_uploader(
        "Upload study materials",
        accept_multiple_files=True,
        key=st.session_state.get("uploader_key", "uploader_1")
    )

    st.markdown("""
    <div class="upload-tip" style="color: #D1D5DB !important;">
        📚 For best retrieval quality, upload related study materials together.
    </div>
    """, unsafe_allow_html=True)

    if st.button("🧹 Clear Chat"):
        st.session_state.chat = []
        if os.path.exists(CHAT_FILE):
            os.remove(CHAT_FILE)

    if st.button("🗑️ Clear Documents"):

        if os.path.exists(DOCS_FILE):
            os.remove(DOCS_FILE)

        documents = {}

        st.session_state["uploader_key"] = str(uuid.uuid4())

        st.success("Documents cleared successfully.")

        st.rerun()

# -------------------------------
# 🏛️ HEADER
# -------------------------------

col1, col2 = st.columns([1, 5])

with col1:
    st.image(logo, width=120)

with col2:
    st.html("""
        <div style="padding-top:10px;">
            <h1 style="
                margin-bottom:0;
                color:#F4F4F5;
                letter-spacing:0.5px;
                font-size:48px;
            ">
                Sensei
            </h1>

            <p style="
                font-size:18px;
                opacity:0.82;
                color:#D1D5DB;
                margin-top:6px;
            ">
                Inspired by Tradition. Powered by Intelligence.
            </p>
        </div>
    """)


# -------------------------------
# 🎨 DOJO CSS
# -------------------------------
# NOTE: dojo_mode is set by the st.toggle inside the sidebar block above.
# The if-block here must always remain AFTER the sidebar block.
if dojo_mode:
    st.markdown(
        """
        <style>

        /* =========================================
           MAIN APP BACKGROUND
        ========================================= */

        .stApp {
            background:
                radial-gradient(ellipse at top left,
                    rgba(61,217,180,0.22) 0%,
                    transparent 38%
                ),
                radial-gradient(ellipse at top right,
                    rgba(212,175,55,0.22) 0%,
                    transparent 38%
                ),
                radial-gradient(ellipse at bottom left,
                    rgba(212,175,55,0.14) 0%,
                    transparent 40%
                ),
                radial-gradient(ellipse at bottom right,
                    rgba(61,217,180,0.14) 0%,
                    transparent 40%
                ),
                linear-gradient(
                    160deg,
                    #080800 0%,
                    #080F06 30%,
                    #060A10 65%,
                    #080600 100%
                );
            color: #F0EDD8;
        }

        /* =========================================
           GLOBAL TEXT — warm gold tint in Dojo Mode
        ========================================= */

        p, li, span, label, .stMarkdown {
            color: #EDE8C8 !important;
        }

        /* Alternate: odd headings teal, even headings gold */
        h1, h3 {
            color: #3DD9B4 !important;
            letter-spacing: 1.5px;
            text-shadow: 0 0 18px rgba(61,217,180,0.50);
        }

        h2, h4 {
            color: #D4AF37 !important;
            letter-spacing: 1.2px;
            text-shadow: 0 0 18px rgba(212,175,55,0.50);
        }

        /* =========================================
           SIDEBAR — gold accent top, teal bottom
        ========================================= */

        section[data-testid="stSidebar"] {
            background:
                linear-gradient(
                    180deg,
                    #0C0A02 0%,
                    #090D06 40%,
                    #050A08 100%
                );
            border-right: 2px solid;
            border-image: linear-gradient(
                180deg,
                #D4AF37,
                #3DD9B4
            ) 1;
            box-shadow: 4px 0 28px rgba(212,175,55,0.12);
        }

        /* =========================================
           HERO HEADER BLOCK — teal left, gold right
        ========================================= */

        [data-testid="stHorizontalBlock"] {
            background:
                linear-gradient(
                    135deg,
                    rgba(18,22,8,0.97),
                    rgba(12,16,20,0.95)
                );
            border-top: 1px solid rgba(212,175,55,0.50);
            border-bottom: 1px solid rgba(61,217,180,0.50);
            border-left: 1px solid rgba(212,175,55,0.30);
            border-right: 1px solid rgba(61,217,180,0.30);
            border-radius: 24px;
            padding: 18px;
            margin-bottom: 24px;
            box-shadow:
                0 0 35px rgba(212,175,55,0.12),
                0 0 35px rgba(61,217,180,0.12),
                inset 0 0 30px rgba(212,175,55,0.03);
        }

        /* =========================================
           CHAT INPUT — gold border, teal focus
        ========================================= */

        .stChatInput textarea {
            background-color: #0A0800 !important;
            color: #EDE8C8 !important;
            border-radius: 16px !important;
            border: 1.5px solid rgba(212,175,55,0.50) !important;
            padding: 12px !important;
            box-shadow: 0 0 14px rgba(212,175,55,0.16) !important;
        }

        .stChatInput textarea:focus {
            border-color: #3DD9B4 !important;
            box-shadow: 0 0 24px rgba(61,217,180,0.35) !important;
        }

        /* =========================================
           BUTTONS — gold gradient
        ========================================= */

        .stButton button {
            background:
                linear-gradient(
                    135deg,
                    #D4AF37,
                    #B8960C
                ) !important;
            color: #0A0800 !important;
            border: none !important;
            border-radius: 14px !important;
            font-weight: 700 !important;
            letter-spacing: 0.5px !important;
            transition: all 0.25s ease;
            box-shadow:
                0 0 16px rgba(212,175,55,0.35),
                0 0 32px rgba(212,175,55,0.12);
        }

        .stButton button:hover {
            transform: translateY(-2px);
            box-shadow:
                0 0 28px rgba(212,175,55,0.55),
                0 0 55px rgba(61,217,180,0.25);
        }

        /* =========================================
           EXPANDERS — teal left gold right gradient
        ========================================= */

        .streamlit-expanderHeader {
            background: linear-gradient(
                90deg,
                rgba(212,175,55,0.14),
                rgba(61,217,180,0.14)
            ) !important;
            border-radius: 12px !important;
            border-top: 1px solid rgba(212,175,55,0.65) !important;
            border-bottom: 1px solid rgba(61,217,180,0.65) !important;
            border-left: 1px solid rgba(212,175,55,0.40) !important;
            border-right: 1px solid rgba(61,217,180,0.40) !important;
            box-shadow:
                0 0 16px rgba(212,175,55,0.18),
                0 0 16px rgba(61,217,180,0.12) !important;
        }

        /* =========================================
           CHAT MESSAGES — dark warm background
        ========================================= */

        .stChatMessage {
            background:
                linear-gradient(
                    135deg,
                    rgba(16,14,4,0.96),
                    rgba(8,12,10,0.94)
                );
            border-radius: 20px;
            padding: 16px;
            border-left: 1px solid rgba(212,175,55,0.25);
            border-right: 1px solid rgba(61,217,180,0.25);
            border-top: 1px solid rgba(212,175,55,0.15);
            border-bottom: 1px solid rgba(61,217,180,0.15);
            backdrop-filter: blur(12px);
            box-shadow:
                0 0 20px rgba(212,175,55,0.07),
                0 0 20px rgba(61,217,180,0.07);
            margin-bottom: 12px;
        }

        /* =========================================
           SCROLLBAR — gold top, teal bottom
        ========================================= */

        ::-webkit-scrollbar { width: 8px; }

        ::-webkit-scrollbar-track {
            background: #080600;
        }

        ::-webkit-scrollbar-thumb {
            background: linear-gradient(180deg, #D4AF37, #3DD9B4);
            border-radius: 20px;
            box-shadow: 0 0 8px rgba(212,175,55,0.4);
        }

        /* =========================================
           HORIZONTAL LINE — gold shimmer
        ========================================= */

        hr {
            border: none;
            height: 1.5px;
            background: linear-gradient(
                90deg,
                transparent,
                #D4AF37 30%,
                #3DD9B4 70%,
                transparent
            );
            box-shadow: 0 0 10px rgba(212,175,55,0.4);
            margin-top: 18px;
            margin-bottom: 18px;
        }

        /* =========================================
           UPLOAD TIP
        ========================================= */

        .upload-tip, .upload-tip p, .upload-tip * {
            background:
                linear-gradient(
                    135deg,
                    rgba(212,175,55,0.14),
                    rgba(61,217,180,0.10)
                );
            border: 1px solid rgba(212,175,55,0.35);
            color: #EDE8C8 !important;
            box-shadow: 0 0 14px rgba(212,175,55,0.12);
            font-style: normal;
        }

        /* =========================================
           DOJO BADGE — animated top strip gold→teal→gold
        ========================================= */

        .stApp::before {
            content: "";
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 3px;
            background: linear-gradient(
                90deg,
                #D4AF37,
                #3DD9B4,
                #D4AF37
            );
            background-size: 200% 100%;
            animation: dojo-strip 3s linear infinite;
            z-index: 9999;
        }

        @keyframes dojo-strip {
            0%   { background-position: 0% 0%; }
            100% { background-position: 200% 0%; }
        }

        </style>
        """,
        unsafe_allow_html=True
    )
# -------------------------------
# 📄 PROCESS FILES
# -------------------------------
# Every time the page reruns (which Streamlit does on any interaction),
# uploaded_files may or may not be present. We always start with an
# empty dict and rebuild from whatever the user has uploaded this run.
documents = {}

if uploaded_files:
    for file in uploaded_files:
        # Each file type goes to a different key in the documents dict.
        # Multiple files of the same type are accumulated with +=
        # so uploading two PDFs merges both into documents["pdf"].
        if file.name.endswith(".pdf"):
            documents["pdf"] = documents.get("pdf", "") + read_pdf(file)
        elif file.name.endswith(".ipynb"):
            documents["notebook"] = documents.get("notebook", "") + "\n\n" + read_ipynb(file)
        elif file.name.endswith(".pptx"):
            documents["slides"] = documents.get("slides", "") + "\n\n" + read_pptx(file)

    # Serialise to JSON string first so we can check its size before writing.
    docs_payload = json.dumps(documents)

    if len(docs_payload) > 10_000_000:
        # 10MB guard — warn the user rather than silently writing a huge file
        # that could fail on disk-quota-limited deployments (e.g. Streamlit Cloud).
        st.sidebar.warning(
            "⚠️ Uploaded content exceeds 10MB. "
            "Some documents may not be saved. Try uploading fewer or smaller files."
        )
    else:
        # Write the documents dict to the session-specific JSON file.
        # This persists documents across page refreshes within the same session.
        with open(DOCS_FILE, "w") as f:
            f.write(docs_payload)

# If no files were uploaded this run but a DOCS_FILE exists from earlier
# in this session, reload it so the user doesn't lose their documents
# just because the page reran without a new upload.
if os.path.exists(DOCS_FILE):
    with open(DOCS_FILE, "r") as f:
        documents = json.load(f)

# -------------------------------
# 💬 CHAT STATE
# -------------------------------
# On first load, check if a saved chat file exists for this session.
# If it does, restore the conversation history so the user sees their
# previous Q&A even after a page refresh. If not, start fresh.
if "chat" not in st.session_state:
    if os.path.exists(CHAT_FILE):
        with open(CHAT_FILE, "r") as f:
            st.session_state.chat = json.load(f)
    else:
        st.session_state.chat = []

# -------------------------------
# 💬 DISPLAY CHAT HISTORY
# -------------------------------
# Replay every saved chat turn on each page load.
# This is how Streamlit creates the illusion of a persistent conversation —
# the entire history is re-rendered from session_state on every rerun.
for chat in st.session_state.chat:
    with st.chat_message("user"):
        st.markdown(chat["question"])

    with st.chat_message("assistant"):
        st.markdown("📌 **Main Explanation**")
        st.markdown(chat["summary"])
        st.markdown("---")

        # Render each source expander (PDF / Notebook / Slides)
        for src, ans in chat["answers"]:

            label = ""
            if src == "pdf":
                label = "🟥 PDF Source — Retrieved Passages"
            elif src == "notebook":
                label = "🟩 Notebook Source — Code & Notes"
            elif src == "slides":
                label = "🟦 Slides Source — Key Points"

            with st.expander(label, expanded=False):
                st.caption("📎 Relevant excerpts retrieved from your uploaded material.")
                st.divider()

                if src == "notebook":
                    # Notebook content needs special handling for images and code fences
                    render_notebook_content(ans)
                else:
                    # PDF and slides: split into readable paragraph chunks with dividers
                    chunks = format_chunks_for_display(ans, src)
                    for i, chunk in enumerate(chunks):
                        st.markdown(chunk)
                        if i < len(chunks) - 1:
                            st.markdown("---")

# -------------------------------
# ❓ QUESTION INPUT & RESPONSE
# -------------------------------
question = st.chat_input("Ask another question...")

# Remind the user to connect their API key if they haven't yet
if not st.session_state.api_configured:
    st.warning("Please connect your Gemini API key from the sidebar.")

# Only process a question if:
#   1. The user typed something (question is not empty)
#   2. At least one document has been uploaded (documents is not empty)
#   3. The API key is connected and valid
if question and documents and st.session_state.api_configured:

    # Render the user's message in the chat
    with st.chat_message("user"):
        st.markdown(question)

    # Run the retrieval engine to find relevant source chunks
    relevant_sources = find_relevant_sources(question, documents)

    answers = []  # Will hold (source_type, retrieved_text) pairs for saving

    with st.chat_message("assistant"):

        if not relevant_sources:
            # No matching chunks found — inform the user clearly
            summary = "❌ Not found in uploaded material"
            st.markdown(summary)
        else:
            # Send retrieved context + question to Gemini and get explanation.
            # Spinner wraps only the API call — not the expander rendering below.
            with st.spinner("Sensei is thinking..."):
                summary = generate_summary(question, relevant_sources)

            # Display the AI-generated explanation first
            st.markdown("📌 **Main Explanation**")
            st.markdown(summary)
            st.markdown("---")

            # Then display the raw source evidence in colour-coded expanders
            for src, text in relevant_sources:
                response = text
                answers.append((src, response))  # Save for chat history

                label = ""
                if src == "pdf":
                    label = "🟥 PDF Source — Retrieved Passages"
                elif src == "notebook":
                    label = "🟩 Notebook Source — Code & Notes"
                elif src == "slides":
                    label = "🟦 Slides Source — Key Points"

                with st.expander(label, expanded=False):
                    st.caption("📎 Relevant excerpts retrieved from your uploaded material.")
                    st.divider()

                    if src == "notebook":
                        render_notebook_content(response)
                    else:
                        chunks = format_chunks_for_display(response, src)
                        for i, chunk in enumerate(chunks):
                            st.markdown(chunk)
                            if i < len(chunks) - 1:
                                st.markdown("---")

    # Append this Q&A turn to the session's chat history
    st.session_state.chat.append({
        "question": question,
        "summary": summary,
        "answers": answers
    })

    # Rolling 50-turn limit: trim oldest entries if history grows too large.
    # Prevents the chat JSON file from growing unboundedly over long sessions.
    if len(st.session_state.chat) > 50:
        st.session_state.chat = st.session_state.chat[-50:]

    # Persist the updated chat history to disk for this session
    with open(CHAT_FILE, "w") as f:
        json.dump(st.session_state.chat, f)

# -------------------------------
# 🔻 FOOTER
# -------------------------------
# Rendered unconditionally — always visible at the bottom of the page
# regardless of whether a question was asked this rerun.
st.markdown("""
<div class="footer">
    Built with Google Gemini • Designed by S.S.R. Yousuf
</div>
""", unsafe_allow_html=True)